-- ============================================================
-- 007_interim_pricing.sql
-- ============================================================
--
-- Replaces the 002 placeholder pricing (flat NGN 1,000 same-zone /
-- NGN 2,000 cross-zone over 14 zones) with the interim formula output:
-- 25 zones, 600 symmetric cross-zone prices, NGN 3,100 - 6,600.
--
--   price = round_to_100(3000 + 60 * haversine_km * 1.4)
--
-- Generated by interim_pricing_generator.py in this directory, which holds
-- the zone coordinates. Source data: interim_zone_pricing_final.json.
--
-- STILL A PLACEHOLDER. These are not client-confirmed rates. The client's
-- own sheet had 21 unpriced pairs and 58 directional mismatches over 15%
-- (see ../client_questions.txt), so it could not be loaded as-is. The
-- zone_pricing.source column records where each row came from, so real
-- prices stay distinguishable. Replacing them is a FULL-TABLE SWAP of
-- zone_pricing, not a patch.
--
-- Zones are upserted BY NAME, never recreated: jobs.pickup_zone_id and
-- dropoff_zone_id are FKs to zones(id), so recreating zones would break
-- historical jobs.
--
-- The 300 pairs below are listed once each and mirrored in SQL, making
-- symmetry an invariant of the migration rather than 600 hand-listed rows
-- that have to agree.
--
-- Idempotent: applied by hand to anx-dev and production, then again by the
-- GitHub integration on merge to main.

-- ── 1. Provenance column ──────────────────────────────────

ALTER TABLE zone_pricing ADD COLUMN IF NOT EXISTS source text;


-- ── 2. Guard ──────────────────────────────────────────────
-- Fail loudly if the database holds a zone this file does not price, rather
-- than silently leaving it unpriced after the swap below.

DO $$
DECLARE stray text;
BEGIN
  SELECT string_agg(name, ', ' ORDER BY name) INTO stray
  FROM zones WHERE name NOT IN ('Airport Road', 'Apo', 'Asokoro', 'Central Area', 'Dakwo', 'Durumi', 'Dutse', 'Galadimawa', 'Garki', 'Gudu', 'Gwarinpa', 'Jabi', 'Jahi', 'Kado', 'Karu', 'Kubwa', 'Kuje', 'Lokogoma', 'Lugbe', 'Maitama', 'Mpape', 'Nyanya', 'Utako', 'Wuse', 'Wuse 2');
  IF stray IS NOT NULL THEN
    RAISE EXCEPTION
      'Zone(s) absent from the interim pricing list would be left unpriced: %', stray;
  END IF;
END $$;


-- ── 3. Zones: add the missing ones, keep existing ids ────

INSERT INTO zones (name)
SELECT v.name
FROM (VALUES
  ('Airport Road'),
  ('Apo'),
  ('Asokoro'),
  ('Central Area'),
  ('Dakwo'),
  ('Durumi'),
  ('Dutse'),
  ('Galadimawa'),
  ('Garki'),
  ('Gudu'),
  ('Gwarinpa'),
  ('Jabi'),
  ('Jahi'),
  ('Kado'),
  ('Karu'),
  ('Kubwa'),
  ('Kuje'),
  ('Lokogoma'),
  ('Lugbe'),
  ('Maitama'),
  ('Mpape'),
  ('Nyanya'),
  ('Utako'),
  ('Wuse'),
  ('Wuse 2')
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM zones z WHERE z.name = v.name);


-- ── 4. Pricing: full replacement ─────────────────────────
-- Joined to zones BY NAME — zone uuids differ between the anx-dev and
-- production projects, so they can never be hardcoded here.

DELETE FROM zone_pricing;

WITH pair(a, b, price) AS (VALUES
  ('Airport Road', 'Apo', 4300),
  ('Airport Road', 'Asokoro', 4800),
  ('Airport Road', 'Central Area', 4600),
  ('Airport Road', 'Dakwo', 3700),
  ('Airport Road', 'Durumi', 4400),
  ('Airport Road', 'Dutse', 4700),
  ('Airport Road', 'Galadimawa', 3700),
  ('Airport Road', 'Garki', 4500),
  ('Airport Road', 'Gudu', 4100),
  ('Airport Road', 'Gwarinpa', 4600),
  ('Airport Road', 'Jabi', 4300),
  ('Airport Road', 'Jahi', 4400),
  ('Airport Road', 'Kado', 4600),
  ('Airport Road', 'Karu', 5300),
  ('Airport Road', 'Kubwa', 4900),
  ('Airport Road', 'Kuje', 4300),
  ('Airport Road', 'Lokogoma', 4100),
  ('Airport Road', 'Lugbe', 3200),
  ('Airport Road', 'Maitama', 4900),
  ('Airport Road', 'Mpape', 4800),
  ('Airport Road', 'Nyanya', 5000),
  ('Airport Road', 'Utako', 4400),
  ('Airport Road', 'Wuse', 4600),
  ('Airport Road', 'Wuse 2', 4600),
  ('Apo', 'Asokoro', 3500),
  ('Apo', 'Central Area', 3600),
  ('Apo', 'Dakwo', 3700),
  ('Apo', 'Durumi', 3500),
  ('Apo', 'Dutse', 4700),
  ('Apo', 'Galadimawa', 3600),
  ('Apo', 'Garki', 3300),
  ('Apo', 'Gudu', 3400),
  ('Apo', 'Gwarinpa', 4200),
  ('Apo', 'Jabi', 4000),
  ('Apo', 'Jahi', 4100),
  ('Apo', 'Kado', 4000),
  ('Apo', 'Karu', 4000),
  ('Apo', 'Kubwa', 5000),
  ('Apo', 'Kuje', 5600),
  ('Apo', 'Lokogoma', 3300),
  ('Apo', 'Lugbe', 4200),
  ('Apo', 'Maitama', 3900),
  ('Apo', 'Mpape', 4000),
  ('Apo', 'Nyanya', 3700),
  ('Apo', 'Utako', 3700),
  ('Apo', 'Wuse', 3600),
  ('Apo', 'Wuse 2', 3700),
  ('Asokoro', 'Central Area', 3400),
  ('Asokoro', 'Dakwo', 4100),
  ('Asokoro', 'Durumi', 3600),
  ('Asokoro', 'Dutse', 4700),
  ('Asokoro', 'Galadimawa', 4100),
  ('Asokoro', 'Garki', 3300),
  ('Asokoro', 'Gudu', 3800),
  ('Asokoro', 'Gwarinpa', 4300),
  ('Asokoro', 'Jabi', 4100),
  ('Asokoro', 'Jahi', 4300),
  ('Asokoro', 'Kado', 3900),
  ('Asokoro', 'Karu', 3600),
  ('Asokoro', 'Kubwa', 5100),
  ('Asokoro', 'Kuje', 6100),
  ('Asokoro', 'Lokogoma', 3800),
  ('Asokoro', 'Lugbe', 4700),
  ('Asokoro', 'Maitama', 3700),
  ('Asokoro', 'Mpape', 3900),
  ('Asokoro', 'Nyanya', 3400),
  ('Asokoro', 'Utako', 3800),
  ('Asokoro', 'Wuse', 3500),
  ('Asokoro', 'Wuse 2', 3600),
  ('Central Area', 'Dakwo', 3900),
  ('Central Area', 'Durumi', 3200),
  ('Central Area', 'Dutse', 4300),
  ('Central Area', 'Galadimawa', 4000),
  ('Central Area', 'Garki', 3200),
  ('Central Area', 'Gudu', 3600),
  ('Central Area', 'Gwarinpa', 3900),
  ('Central Area', 'Jabi', 3700),
  ('Central Area', 'Jahi', 3800),
  ('Central Area', 'Kado', 3500),
  ('Central Area', 'Karu', 4000),
  ('Central Area', 'Kubwa', 4700),
  ('Central Area', 'Kuje', 5900),
  ('Central Area', 'Lokogoma', 3800),
  ('Central Area', 'Lugbe', 4500),
  ('Central Area', 'Maitama', 3300),
  ('Central Area', 'Mpape', 3500),
  ('Central Area', 'Nyanya', 3800),
  ('Central Area', 'Utako', 3400),
  ('Central Area', 'Wuse', 3100),
  ('Central Area', 'Wuse 2', 3200),
  ('Dakwo', 'Durumi', 3700),
  ('Dakwo', 'Dutse', 4400),
  ('Dakwo', 'Galadimawa', 3200),
  ('Dakwo', 'Garki', 3800),
  ('Dakwo', 'Gudu', 3400),
  ('Dakwo', 'Gwarinpa', 4100),
  ('Dakwo', 'Jabi', 3800),
  ('Dakwo', 'Jahi', 3900),
  ('Dakwo', 'Kado', 4000),
  ('Dakwo', 'Karu', 4600),
  ('Dakwo', 'Kubwa', 4700),
  ('Dakwo', 'Kuje', 5000),
  ('Dakwo', 'Lokogoma', 3400),
  ('Dakwo', 'Lugbe', 3600),
  ('Dakwo', 'Maitama', 4200),
  ('Dakwo', 'Mpape', 4200),
  ('Dakwo', 'Nyanya', 4300),
  ('Dakwo', 'Utako', 3800),
  ('Dakwo', 'Wuse', 3900),
  ('Dakwo', 'Wuse 2', 3900),
  ('Durumi', 'Dutse', 4200),
  ('Durumi', 'Galadimawa', 3800),
  ('Durumi', 'Garki', 3200),
  ('Durumi', 'Gudu', 3300),
  ('Durumi', 'Gwarinpa', 3800),
  ('Durumi', 'Jabi', 3600),
  ('Durumi', 'Jahi', 3700),
  ('Durumi', 'Kado', 3500),
  ('Durumi', 'Karu', 4200),
  ('Durumi', 'Kubwa', 4600),
  ('Durumi', 'Kuje', 5700),
  ('Durumi', 'Lokogoma', 3600),
  ('Durumi', 'Lugbe', 4300),
  ('Durumi', 'Maitama', 3500),
  ('Durumi', 'Mpape', 3600),
  ('Durumi', 'Nyanya', 3900),
  ('Durumi', 'Utako', 3300),
  ('Durumi', 'Wuse', 3200),
  ('Durumi', 'Wuse 2', 3200),
  ('Dutse', 'Galadimawa', 4600),
  ('Dutse', 'Garki', 4500),
  ('Dutse', 'Gudu', 4300),
  ('Dutse', 'Gwarinpa', 3500),
  ('Dutse', 'Jabi', 3700),
  ('Dutse', 'Jahi', 3500),
  ('Dutse', 'Kado', 3800),
  ('Dutse', 'Karu', 5300),
  ('Dutse', 'Kubwa', 3400),
  ('Dutse', 'Kuje', 5700),
  ('Dutse', 'Lokogoma', 4700),
  ('Dutse', 'Lugbe', 4800),
  ('Dutse', 'Maitama', 4200),
  ('Dutse', 'Mpape', 4000),
  ('Dutse', 'Nyanya', 5100),
  ('Dutse', 'Utako', 3900),
  ('Dutse', 'Wuse', 4200),
  ('Dutse', 'Wuse 2', 4100),
  ('Galadimawa', 'Garki', 3800),
  ('Galadimawa', 'Gudu', 3400),
  ('Galadimawa', 'Gwarinpa', 4200),
  ('Galadimawa', 'Jabi', 3900),
  ('Galadimawa', 'Jahi', 4100),
  ('Galadimawa', 'Kado', 4100),
  ('Galadimawa', 'Karu', 4600),
  ('Galadimawa', 'Kubwa', 4800),
  ('Galadimawa', 'Kuje', 5000),
  ('Galadimawa', 'Lokogoma', 3300),
  ('Galadimawa', 'Lugbe', 3600),
  ('Galadimawa', 'Maitama', 4300),
  ('Galadimawa', 'Mpape', 4300),
  ('Galadimawa', 'Nyanya', 4300),
  ('Galadimawa', 'Utako', 3900),
  ('Galadimawa', 'Wuse', 4000),
  ('Galadimawa', 'Wuse 2', 4000),
  ('Garki', 'Gudu', 3400),
  ('Garki', 'Gwarinpa', 4000),
  ('Garki', 'Jabi', 3800),
  ('Garki', 'Jahi', 3900),
  ('Garki', 'Kado', 3700),
  ('Garki', 'Karu', 4000),
  ('Garki', 'Kubwa', 4800),
  ('Garki', 'Kuje', 5800),
  ('Garki', 'Lokogoma', 3600),
  ('Garki', 'Lugbe', 4400),
  ('Garki', 'Maitama', 3600),
  ('Garki', 'Mpape', 3700),
  ('Garki', 'Nyanya', 3700),
  ('Garki', 'Utako', 3500),
  ('Garki', 'Wuse', 3300),
  ('Garki', 'Wuse 2', 3400),
  ('Gudu', 'Gwarinpa', 3900),
  ('Gudu', 'Jabi', 3600),
  ('Gudu', 'Jahi', 3700),
  ('Gudu', 'Kado', 3700),
  ('Gudu', 'Karu', 4300),
  ('Gudu', 'Kubwa', 4600),
  ('Gudu', 'Kuje', 5400),
  ('Gudu', 'Lokogoma', 3400),
  ('Gudu', 'Lugbe', 4000),
  ('Gudu', 'Maitama', 3800),
  ('Gudu', 'Mpape', 3800),
  ('Gudu', 'Nyanya', 4100),
  ('Gudu', 'Utako', 3500),
  ('Gudu', 'Wuse', 3500),
  ('Gudu', 'Wuse 2', 3500),
  ('Gwarinpa', 'Jabi', 3300),
  ('Gwarinpa', 'Jahi', 3200),
  ('Gwarinpa', 'Kado', 3300),
  ('Gwarinpa', 'Karu', 4900),
  ('Gwarinpa', 'Kubwa', 3800),
  ('Gwarinpa', 'Kuje', 5700),
  ('Gwarinpa', 'Lokogoma', 4300),
  ('Gwarinpa', 'Lugbe', 4600),
  ('Gwarinpa', 'Maitama', 3700),
  ('Gwarinpa', 'Mpape', 3500),
  ('Gwarinpa', 'Nyanya', 4600),
  ('Gwarinpa', 'Utako', 3500),
  ('Gwarinpa', 'Wuse', 3700),
  ('Gwarinpa', 'Wuse 2', 3700),
  ('Jabi', 'Jahi', 3200),
  ('Jabi', 'Kado', 3300),
  ('Jabi', 'Karu', 4700),
  ('Jabi', 'Kubwa', 4000),
  ('Jabi', 'Kuje', 5500),
  ('Jabi', 'Lokogoma', 4000),
  ('Jabi', 'Lugbe', 4300),
  ('Jabi', 'Maitama', 3700),
  ('Jabi', 'Mpape', 3600),
  ('Jabi', 'Nyanya', 4400),
  ('Jabi', 'Utako', 3300),
  ('Jabi', 'Wuse', 3600),
  ('Jabi', 'Wuse 2', 3500),
  ('Jahi', 'Kado', 3400),
  ('Jahi', 'Karu', 4900),
  ('Jahi', 'Kubwa', 3900),
  ('Jahi', 'Kuje', 5500),
  ('Jahi', 'Lokogoma', 4100),
  ('Jahi', 'Lugbe', 4400),
  ('Jahi', 'Maitama', 3800),
  ('Jahi', 'Mpape', 3600),
  ('Jahi', 'Nyanya', 4600),
  ('Jahi', 'Utako', 3400),
  ('Jahi', 'Wuse', 3700),
  ('Jahi', 'Wuse 2', 3700),
  ('Kado', 'Karu', 4600),
  ('Kado', 'Kubwa', 4100),
  ('Kado', 'Kuje', 5800),
  ('Kado', 'Lokogoma', 4100),
  ('Kado', 'Lugbe', 4600),
  ('Kado', 'Maitama', 3400),
  ('Kado', 'Mpape', 3300),
  ('Kado', 'Nyanya', 4300),
  ('Kado', 'Utako', 3200),
  ('Kado', 'Wuse', 3400),
  ('Kado', 'Wuse 2', 3300),
  ('Karu', 'Kubwa', 5700),
  ('Karu', 'Kuje', 6600),
  ('Karu', 'Lokogoma', 4200),
  ('Karu', 'Lugbe', 5100),
  ('Karu', 'Maitama', 4200),
  ('Karu', 'Mpape', 4400),
  ('Karu', 'Nyanya', 3300),
  ('Karu', 'Utako', 4400),
  ('Karu', 'Wuse', 4200),
  ('Karu', 'Wuse 2', 4200),
  ('Kubwa', 'Kuje', 5700),
  ('Kubwa', 'Lokogoma', 5000),
  ('Kubwa', 'Lugbe', 4900),
  ('Kubwa', 'Maitama', 4500),
  ('Kubwa', 'Mpape', 4300),
  ('Kubwa', 'Nyanya', 5400),
  ('Kubwa', 'Utako', 4300),
  ('Kubwa', 'Wuse', 4500),
  ('Kubwa', 'Wuse 2', 4500),
  ('Kuje', 'Lokogoma', 5400),
  ('Kuje', 'Lugbe', 4400),
  ('Kuje', 'Maitama', 6100),
  ('Kuje', 'Mpape', 6100),
  ('Kuje', 'Nyanya', 6300),
  ('Kuje', 'Utako', 5700),
  ('Kuje', 'Wuse', 5900),
  ('Kuje', 'Wuse 2', 5900),
  ('Lokogoma', 'Lugbe', 3900),
  ('Lokogoma', 'Maitama', 4100),
  ('Lokogoma', 'Mpape', 4200),
  ('Lokogoma', 'Nyanya', 3900),
  ('Lokogoma', 'Utako', 3800),
  ('Lokogoma', 'Wuse', 3800),
  ('Lokogoma', 'Wuse 2', 3800),
  ('Lugbe', 'Maitama', 4800),
  ('Lugbe', 'Mpape', 4800),
  ('Lugbe', 'Nyanya', 4900),
  ('Lugbe', 'Utako', 4400),
  ('Lugbe', 'Wuse', 4500),
  ('Lugbe', 'Wuse 2', 4500),
  ('Maitama', 'Mpape', 3200),
  ('Maitama', 'Nyanya', 4000),
  ('Maitama', 'Utako', 3500),
  ('Maitama', 'Wuse', 3300),
  ('Maitama', 'Wuse 2', 3300),
  ('Mpape', 'Nyanya', 4200),
  ('Mpape', 'Utako', 3400),
  ('Mpape', 'Wuse', 3400),
  ('Mpape', 'Wuse 2', 3300),
  ('Nyanya', 'Utako', 4200),
  ('Nyanya', 'Wuse', 3900),
  ('Nyanya', 'Wuse 2', 4000),
  ('Utako', 'Wuse', 3300),
  ('Utako', 'Wuse 2', 3200),
  ('Wuse', 'Wuse 2', 3100)
), directed AS (
  SELECT a AS from_name, b AS to_name, price FROM pair
  UNION ALL
  SELECT b, a, price FROM pair          -- mirror: pricing is symmetric
)
INSERT INTO zone_pricing (from_zone_id, to_zone_id, base_price, source)
SELECT zf.id, zt.id, d.price, 'interim-formula-2026-09'
FROM directed d
JOIN zones zf ON zf.name = d.from_name
JOIN zones zt ON zt.name = d.to_name;


-- ── 5. Same-zone base fee ────────────────────────────────
-- The generated data is cross-zone only, but the API looks up an exact
-- (from, to) pair, so a same-zone delivery would fail with "No pricing for
-- this zone combination" without these rows.
--
-- NGN 3,000 is what the formula yields at zero distance: the distance term
-- goes to zero, leaving BASE_FEE. So the value is method-consistent. It still
-- carries its own source marker because the source data has no same-zone
-- entries at all — these rows extrapolate the formula to a case the client
-- never priced, and that assumption needs confirming separately.

INSERT INTO zone_pricing (from_zone_id, to_zone_id, base_price, source)
SELECT z.id, z.id, 3000, 'interim-samezone-basefee-2026-09'
FROM zones z;


-- ── 6. Uniqueness ────────────────────────────────────────
-- The API reads pricing with .maybeSingle(), which errors on duplicates, so a
-- duplicate pair would break job creation outright. Postgres has no
-- ADD CONSTRAINT IF NOT EXISTS, hence the catalog check.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    WHERE t.relname = 'zone_pricing' AND c.conname = 'zone_pricing_from_to_key'
  ) THEN
    ALTER TABLE zone_pricing
      ADD CONSTRAINT zone_pricing_from_to_key UNIQUE (from_zone_id, to_zone_id);
  END IF;
END $$;
